require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BrewingsController do

  def mock_brewing(stubs={})
    @mock_brewing ||= mock_model(Brewing, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all brewings as @brewings" do
      Brewing.stub(:all) { [mock_brewing] }
      get :index
      assigns(:brewings).should eq([mock_brewing])
    end
  end

  describe "GET show" do
    it "assigns the requested brewing as @brewing" do
      Brewing.stub(:find).with("37") { mock_brewing }
      get :show, :id => "37"
      assigns(:brewing).should be(mock_brewing)
    end
  end

  describe "GET new" do
    it "assigns a new brewing as @brewing" do
      Brewing.stub(:new) { mock_brewing }
      get :new
      assigns(:brewing).should be(mock_brewing)
    end
  end

  describe "GET edit" do
    it "assigns the requested brewing as @brewing" do
      Brewing.stub(:find).with("37") { mock_brewing }
      get :edit, :id => "37"
      assigns(:brewing).should be(mock_brewing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created brewing as @brewing" do
        Brewing.stub(:new).with({'these' => 'params'}) { mock_brewing(:save => true) }
        post :create, :brewing => {'these' => 'params'}
        assigns(:brewing).should be(mock_brewing)
      end

      it "redirects to the created brewing" do
        Brewing.stub(:new) { mock_brewing(:save => true) }
        post :create, :brewing => {}
        response.should redirect_to(brewing_url(mock_brewing))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved brewing as @brewing" do
        Brewing.stub(:new).with({'these' => 'params'}) { mock_brewing(:save => false) }
        post :create, :brewing => {'these' => 'params'}
        assigns(:brewing).should be(mock_brewing)
      end

      it "re-renders the 'new' template" do
        Brewing.stub(:new) { mock_brewing(:save => false) }
        post :create, :brewing => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested brewing" do
        Brewing.stub(:find).with("37") { mock_brewing }
        mock_brewing.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :brewing => {'these' => 'params'}
      end

      it "assigns the requested brewing as @brewing" do
        Brewing.stub(:find) { mock_brewing(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:brewing).should be(mock_brewing)
      end

      it "redirects to the brewing" do
        Brewing.stub(:find) { mock_brewing(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(brewing_url(mock_brewing))
      end
    end

    describe "with invalid params" do
      it "assigns the brewing as @brewing" do
        Brewing.stub(:find) { mock_brewing(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:brewing).should be(mock_brewing)
      end

      it "re-renders the 'edit' template" do
        Brewing.stub(:find) { mock_brewing(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested brewing" do
      Brewing.stub(:find).with("37") { mock_brewing }
      mock_brewing.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the brewings list" do
      Brewing.stub(:find) { mock_brewing }
      delete :destroy, :id => "1"
      response.should redirect_to(brewings_url)
    end
  end

end
