require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BrewTypesController do

  def mock_brew_type(stubs={})
    @mock_brew_type ||= mock_model(BrewType, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all brew_types as @brew_types" do
      BrewType.stub(:all) { [mock_brew_type] }
      get :index
      assigns(:brew_types).should eq([mock_brew_type])
    end
  end

  describe "GET show" do
    it "assigns the requested brew_type as @brew_type" do
      BrewType.stub(:find).with("37") { mock_brew_type }
      get :show, :id => "37"
      assigns(:brew_type).should be(mock_brew_type)
    end
  end

  describe "GET new" do
    it "assigns a new brew_type as @brew_type" do
      BrewType.stub(:new) { mock_brew_type }
      get :new
      assigns(:brew_type).should be(mock_brew_type)
    end
  end

  describe "GET edit" do
    it "assigns the requested brew_type as @brew_type" do
      BrewType.stub(:find).with("37") { mock_brew_type }
      get :edit, :id => "37"
      assigns(:brew_type).should be(mock_brew_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created brew_type as @brew_type" do
        BrewType.stub(:new).with({'these' => 'params'}) { mock_brew_type(:save => true) }
        post :create, :brew_type => {'these' => 'params'}
        assigns(:brew_type).should be(mock_brew_type)
      end

      it "redirects to the created brew_type" do
        BrewType.stub(:new) { mock_brew_type(:save => true) }
        post :create, :brew_type => {}
        response.should redirect_to(brew_type_url(mock_brew_type))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved brew_type as @brew_type" do
        BrewType.stub(:new).with({'these' => 'params'}) { mock_brew_type(:save => false) }
        post :create, :brew_type => {'these' => 'params'}
        assigns(:brew_type).should be(mock_brew_type)
      end

      it "re-renders the 'new' template" do
        BrewType.stub(:new) { mock_brew_type(:save => false) }
        post :create, :brew_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested brew_type" do
        BrewType.stub(:find).with("37") { mock_brew_type }
        mock_brew_type.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :brew_type => {'these' => 'params'}
      end

      it "assigns the requested brew_type as @brew_type" do
        BrewType.stub(:find) { mock_brew_type(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:brew_type).should be(mock_brew_type)
      end

      it "redirects to the brew_type" do
        BrewType.stub(:find) { mock_brew_type(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(brew_type_url(mock_brew_type))
      end
    end

    describe "with invalid params" do
      it "assigns the brew_type as @brew_type" do
        BrewType.stub(:find) { mock_brew_type(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:brew_type).should be(mock_brew_type)
      end

      it "re-renders the 'edit' template" do
        BrewType.stub(:find) { mock_brew_type(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested brew_type" do
      BrewType.stub(:find).with("37") { mock_brew_type }
      mock_brew_type.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the brew_types list" do
      BrewType.stub(:find) { mock_brew_type }
      delete :destroy, :id => "1"
      response.should redirect_to(brew_types_url)
    end
  end

end
