require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ReadingsController do

  def mock_reading(stubs={})
    @mock_reading ||= mock_model(Reading, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all readings as @readings" do
      Reading.stub(:all) { [mock_reading] }
      get :index
      assigns(:readings).should eq([mock_reading])
    end
  end

  describe "GET show" do
    it "assigns the requested reading as @reading" do
      Reading.stub(:find).with("37") { mock_reading }
      get :show, :id => "37"
      assigns(:reading).should be(mock_reading)
    end
  end

  describe "GET new" do
    it "assigns a new reading as @reading" do
      Reading.stub(:new) { mock_reading }
      get :new
      assigns(:reading).should be(mock_reading)
    end
  end

  describe "GET edit" do
    it "assigns the requested reading as @reading" do
      Reading.stub(:find).with("37") { mock_reading }
      get :edit, :id => "37"
      assigns(:reading).should be(mock_reading)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created reading as @reading" do
        Reading.stub(:new).with({'these' => 'params'}) { mock_reading(:save => true) }
        post :create, :reading => {'these' => 'params'}
        assigns(:reading).should be(mock_reading)
      end

      it "redirects to the created reading" do
        Reading.stub(:new) { mock_reading(:save => true) }
        post :create, :reading => {}
        response.should redirect_to(reading_url(mock_reading))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reading as @reading" do
        Reading.stub(:new).with({'these' => 'params'}) { mock_reading(:save => false) }
        post :create, :reading => {'these' => 'params'}
        assigns(:reading).should be(mock_reading)
      end

      it "re-renders the 'new' template" do
        Reading.stub(:new) { mock_reading(:save => false) }
        post :create, :reading => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reading" do
        Reading.stub(:find).with("37") { mock_reading }
        mock_reading.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :reading => {'these' => 'params'}
      end

      it "assigns the requested reading as @reading" do
        Reading.stub(:find) { mock_reading(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:reading).should be(mock_reading)
      end

      it "redirects to the reading" do
        Reading.stub(:find) { mock_reading(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(reading_url(mock_reading))
      end
    end

    describe "with invalid params" do
      it "assigns the reading as @reading" do
        Reading.stub(:find) { mock_reading(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:reading).should be(mock_reading)
      end

      it "re-renders the 'edit' template" do
        Reading.stub(:find) { mock_reading(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reading" do
      Reading.stub(:find).with("37") { mock_reading }
      mock_reading.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the readings list" do
      Reading.stub(:find) { mock_reading }
      delete :destroy, :id => "1"
      response.should redirect_to(readings_url)
    end
  end

end
